name: CICD
on:
    push:
        branches:
            - master
        paths-ignore:
            - 'helm/**'
            - 'k8s/**'
            - 'README.md'

jobs:
    build:
        runs-on: ubuntu-server
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Go Language
              uses: actions/setup-go@v2
              with:
                go-version: 1.21.10

            - name: Build Artifact
              run: go build -o go-web-app

            - name: Run Test cases
              run: go test ./...

    codequality:
        runs-on: ubuntu-server
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.56.2
            
    push:
        needs: build
        runs-on: ubuntu-server
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Docker BuildX
              uses: docker/setup-buildx-action@v1

            - name: Login to Dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_LOGIN_USERNAME}}
                password: ${{secrets.DOCKER_LOGIN_PASSWORD}}
            
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tag: ${{secrets.DOCKER_LOGIN_USERNAME}}/go-web-app:${{github.run_id}}
        
    update-newtag-to-helmchat:
        needs: push
        runs-on: ubuntu-server
        steps:
            - name: Checkout-Repository
              uses: actions/checkout@v4
              with:
                token: ${{secrets.GITHUB_TOKEN}}
            
            - name: Update New Tag in helm chart values.yaml file
              run: |
                   sed -i 's/tag: .*/tag: "${{github.run_id}}"/g' helm/go-web-app-chart/values.yaml
            
            - name: Commit And Push Changes
              run: |
                   git config --global user.email 'bhargavharshith@gmail.com'
                   git config --global user.name 'BhargavHarshith'
                   git add helm/go-web-app-chart/values.yaml
                   git commit -m "Updated Docker Image with version number ${{github.run_id}}"
                   git push
